import {
    Loader2,
    Mail,
    Github,
    Chrome,
    Facebook,
    Twitter,
    Instagram,
    Copy,
    Calendar,
    X,
    Paperclip,
    Edit2,
    Trash2,
    MessageSquare,
    Send,
    Reply,
    Smile,
    Search,
    Plus,
    Maximize2,
    File,
    Lock,
    Share2,
    ArrowLeft
} from 'lucide-react';
  
export const Icons = {
    spinner: Loader2,
    google: Chrome,
    github: Github,
    mail: Mail,
    calendar: Calendar,
    x: X,
    paperclip: Paperclip,
    edit: Edit2,
    trash: Trash2,
    messageSquare: MessageSquare,
    send: Send,
    reply: Reply,
    smile: Smile,
    search: Search,
    plus: Plus,
    maximize2: Maximize2,
    file: File,
    lock: Lock,
    facebook: Facebook,
    instagram: Instagram,
    twitter: Twitter,
    copy: Copy,
    share2: Share2,
    arrowLeft: ArrowLeft
};
